[package]
name = "openstratos-ci"
version = "0.1.0"
authors = ["Razican <razican@protonmail.ch>"]

[dependencies]
clap = "2.24"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
error-chain = "0.10"
colored = "1.5"
reqwest = "0.6"
